package examples

import kotlinx.coroutines.*
import utils.log

/**
 * Example 1 PRESENTATION
 * ---------
 * - Check the log function and to see the coroutine name you can add VM argument: -Dkotlinx.coroutines.debug
 * - Check doSomething continuation autogenerated parameter by the Kotlin compiler in the Bytecode
 * - Use the job (join & cancel)
 */

suspend fun doSomething() {
    delay(1000)
    log("Foo")
}

fun main() {
    runBlocking {
        val job = launch(context = Dispatchers.Default) {
            doSomething()
        }
        job.join()
    }
}
